### ISSUE TITLE
[Question] Releasing a nuget package

### ISSUE THREAD

**Issue by Thundernerd** [nickelc/modio.net#1]
Hi there,

Will this be released as a package on nuget (or any other source like that)?

Cheers

**Comment by nickelc** [comment]
When I thought about it at the time, I was turned off by the fact that nuget.org requires a Microsoft account.
Are there any popular alternatives?

**Comment by Thundernerd** [comment]
GitHub has a nuget registry as well, though for that one you need to be authenticated whenever you want to download a package, which is even more annoying :)
