### ISSUE TITLE
Modio.ApiException.GetApiError  throws an exception

### ISSUE THREAD

**Issue by jswigart** [nickelc/modio.net#2]
Whenever I get an API error, I get the following exception

Exception thrown: 'System.NotSupportedException' in System.Text.Json.dll
Deserialization of reference types without parameterless constructor is not supported. Type 'Modio.Models.ApiError'

The fix for this is simply to add a default constructor to class ApiError

**Comment by nickelc** [comment]
What framework version do you use?

**Comment by nickelc** [comment]
Ok, I found a link related to the issue.
https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/non-public-parameterless-constructors-not-used-for-deserialization

It's fixed with [ebd5427](https://github.com/nickelc/modio.net/commit/ebd5427b2c529ddd513b748d7ba431ce95ec7ff6).

**Comment by jswigart** [comment]
Unfortunately this app is still dotnet core 3.1
