### ISSUE TITLE
Updating Mod Logo Fails

### ISSUE THREAD

**Issue by jswigart** [nickelc/modio.net#3]
Given the following code, updating the logo for a mod fails.

```
NewModMedia newMedia = new NewModMedia();
newMedia.Logo = usablePreview;
existingMod.AddMedia(newMedia).Wait();
```

with the following error

```
{
   "error":{
      "code":422,
      "error_ref":13009,
      "message":"Validation Failed. Please see below to fix invalid input:",
      "errors":{
         "logo":"The logo must be an image."
      }
   }
}
```

The fix for this is very simple

<img width="278" alt="image" src="https://user-images.githubusercontent.com/4065267/200214664-4e68d6ba-beb7-4c75-b8b1-3165f9a3b3e4.png">

**Comment by nickelc** [comment]
Thank you for the report.
It's fixed in [fee0d13](https://github.com/nickelc/modio.net/commit/fee0d13c9d7a39aaebc99f2179bcc2e1a778832b).
